"""
download_vendors.py — Fetch all third-party CSS/JS/font assets and store them locally.

Run once (or whenever you want to refresh):
    python download_vendors.py

What it downloads
-----------------
  app/static/js/tailwind.js          Tailwind CSS Play CDN (browser-side JIT runtime)
  app/static/js/chart.umd.min.js     Chart.js 4.4.0
  app/static/fonts/Ubuntu-*.woff2    Ubuntu typeface (all 8 variants used by the app)
  app/static/css/fonts.css           @font-face declarations pointing to local files
"""

import os
import re
import sys
import urllib.request
import urllib.error

BASE = os.path.dirname(os.path.abspath(__file__))
STATIC = os.path.join(BASE, "app", "static")
JS_DIR = os.path.join(STATIC, "js")
FONT_DIR = os.path.join(STATIC, "fonts")
CSS_DIR = os.path.join(STATIC, "css")

for d in (JS_DIR, FONT_DIR, CSS_DIR):
    os.makedirs(d, exist_ok=True)

# Modern browser UA so Google Fonts returns WOFF2 (not older formats)
MODERN_UA = (
    "Mozilla/5.0 (Windows NT 10.0; Win64; x64) "
    "AppleWebKit/537.36 (KHTML, like Gecko) "
    "Chrome/124.0.0.0 Safari/537.36"
)


def fetch(url: str, dest: str, headers: dict | None = None) -> bool:
    if os.path.exists(dest):
        print(f"  [skip]  {os.path.relpath(dest, BASE)}  (already exists)")
        return True
    print(f"  [get]   {url}")
    req = urllib.request.Request(url, headers=headers or {})
    try:
        with urllib.request.urlopen(req, timeout=30) as resp:
            data = resp.read()
        with open(dest, "wb") as f:
            f.write(data)
        size_kb = len(data) // 1024
        print(f"  [ok]    {os.path.relpath(dest, BASE)}  ({size_kb} KB)")
        return True
    except urllib.error.URLError as exc:
        print(f"  [ERR]   {url} → {exc}", file=sys.stderr)
        return False


def fetch_text(url: str, headers: dict | None = None) -> str | None:
    req = urllib.request.Request(url, headers=headers or {})
    try:
        with urllib.request.urlopen(req, timeout=30) as resp:
            return resp.read().decode("utf-8")
    except urllib.error.URLError as exc:
        print(f"  [ERR]   {url} → {exc}", file=sys.stderr)
        return None


# ── 1. Tailwind Play CDN ──────────────────────────────────────────────────────
# cdn.tailwindcss.com requires a browser User-Agent; use versioned URL.
print("\n[1/3] Tailwind CSS Play CDN 3.4.17")
fetch(
    "https://cdn.tailwindcss.com/3.4.17",
    os.path.join(JS_DIR, "tailwind.js"),
    headers={"User-Agent": MODERN_UA},
)

# ── 2. Chart.js ──────────────────────────────────────────────────────────────
print("\n[2/3] Chart.js 4.4.0")
fetch(
    "https://cdn.jsdelivr.net/npm/chart.js@4.4.0/dist/chart.umd.min.js",
    os.path.join(JS_DIR, "chart.umd.min.js"),
)

# ── 3. Ubuntu font (Google Fonts → WOFF2 files + local CSS) ──────────────────
print("\n[3/3] Ubuntu font (Google Fonts)")

GOOGLE_FONT_URL = (
    "https://fonts.googleapis.com/css2"
    "?family=Ubuntu:ital,wght@0,300;0,400;0,500;0,700;1,300;1,400;1,500;1,700"
    "&display=swap"
)

css_text = fetch_text(GOOGLE_FONT_URL, headers={"User-Agent": MODERN_UA})
if not css_text:
    print("  [ERR]  Could not download Google Fonts CSS — skipping font step.", file=sys.stderr)
    sys.exit(1)

# Extract all WOFF2 src URLs from the CSS response
woff2_urls = re.findall(r"url\((https://fonts\.gstatic\.com[^)]+\.woff2)\)", css_text)
print(f"  Found {len(woff2_urls)} WOFF2 variant(s)")

# Map: url → local filename  (based on the hash segment in the URL)
url_to_local: dict[str, str] = {}
for url in woff2_urls:
    # filename: Ubuntu-<hash>.woff2
    slug = url.rsplit("/", 1)[-1]          # e.g. abc123.woff2
    local_name = f"Ubuntu-{slug}"
    dest = os.path.join(FONT_DIR, local_name)
    fetch(url, dest, headers={"User-Agent": MODERN_UA})
    url_to_local[url] = local_name

# Build local CSS with @font-face pointing to our downloaded files
def rewrite_url(match: re.Match) -> str:
    original_url = match.group(1)
    local_name = url_to_local.get(original_url)
    if local_name:
        return f"url(../fonts/{local_name})"
    return match.group(0)

local_css = re.sub(
    r"url\((https://fonts\.gstatic\.com[^)]+\.woff2)\)",
    rewrite_url,
    css_text,
)
# Strip the Google Fonts comment header to keep only @font-face blocks
local_css = "\n".join(
    line for line in local_css.splitlines()
    if not line.strip().startswith("/*") and not line.strip() == "*/"
).strip()

fonts_css_path = os.path.join(CSS_DIR, "fonts.css")
with open(fonts_css_path, "w", encoding="utf-8") as f:
    f.write("/* Ubuntu font — self-hosted, generated by download_vendors.py */\n\n")
    f.write(local_css)
    f.write("\n")
print(f"  [ok]    app/static/css/fonts.css  (written)")

print("\nDone. All vendor assets are now in app/static/.")
print("Templates already updated to use these local paths.")
